-- Create jobs table
CREATE TABLE IF NOT EXISTS public.jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    department TEXT NOT NULL,
    location TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('Full-time', 'Part-time', 'Contract', 'Temporary', 'Seasonal')),
    experience TEXT NOT NULL,
    description TEXT NOT NULL,
    responsibilities JSONB NOT NULL DEFAULT '[]'::jsonb,
    requirements JSONB NOT NULL DEFAULT '[]'::jsonb,
    benefits JSONB NOT NULL DEFAULT '[]'::jsonb,
    posted_date DATE NOT NULL DEFAULT CURRENT_DATE,
    closing_date DATE,
    featured BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Add trigger for updated_at
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = now(); 
   RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_jobs_modtime
BEFORE UPDATE ON public.jobs
FOR EACH ROW
EXECUTE FUNCTION update_modified_column();

-- Set up RLS policies
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to view jobs (admin area)
CREATE POLICY "Allow authenticated users to select from jobs"
ON public.jobs FOR SELECT
USING (auth.role() = 'authenticated');

-- Allow authenticated users to create jobs (admin area)
CREATE POLICY "Allow authenticated users to insert into jobs"
ON public.jobs FOR INSERT
WITH CHECK (auth.role() = 'authenticated');

-- Allow authenticated users to edit jobs (admin area)
CREATE POLICY "Allow authenticated users to update jobs"
ON public.jobs FOR UPDATE
USING (auth.role() = 'authenticated');

-- Allow authenticated users to delete jobs (admin area)
CREATE POLICY "Allow authenticated users to delete from jobs"
ON public.jobs FOR DELETE
USING (auth.role() = 'authenticated');

-- Allow public (anonymous) users to view jobs (frontend)
CREATE POLICY "Allow public to view jobs"
ON public.jobs FOR SELECT
USING (true);

-- Add example jobs
INSERT INTO public.jobs (
    title, 
    department, 
    location, 
    type, 
    experience, 
    description, 
    responsibilities, 
    requirements, 
    benefits, 
    posted_date, 
    closing_date, 
    featured
)
VALUES
(
    'Senior Drywall Finisher',
    'Production',
    'Calgary, AB',
    'Full-time',
    '5+ years',
    'Join our team of skilled craftsmen delivering top-quality drywall finishing services to residential and commercial clients.',
    '["Execute Level 5 finishing and specialty textures", "Manage small teams of junior craftsmen", "Ensure quality control on projects", "Maintain equipment and manage inventory", "Communicate effectively with project managers and clients"]',
    '["Minimum 5 years experience in drywall finishing", "Expert knowledge of various texture techniques", "Valid driver''s license and reliable transportation", "Strong communication skills", "Ability to work flexible hours when needed"]',
    '["Competitive pay: $28-35/hr based on experience", "Health insurance options", "Retirement plan with company match", "Paid time off and holidays", "Tool and vehicle allowance", "Ongoing professional development"]',
    CURRENT_DATE - INTERVAL '30 days',
    CURRENT_DATE + INTERVAL '30 days',
    true
),
(
    'Project Estimator',
    'Sales',
    'Calgary, AB',
    'Full-time',
    '3+ years',
    'Calculate project costs and prepare detailed quotes for residential and commercial drywall and finishing projects.',
    '["Visit sites and prepare thorough assessments", "Calculate material and labor requirements", "Prepare detailed quotes for clients", "Coordinate with production team on job requirements", "Maintain client relationships during the estimation process"]',
    '["Minimum 3 years experience in construction estimation", "Knowledge of drywall installation and finishing processes", "Excellent math and budgeting skills", "Strong attention to detail", "Computer proficiency (Excel, estimation software)"]',
    '["Competitive salary: $55,000-70,000 based on experience", "Performance bonuses", "Comprehensive health benefits", "Retirement plan with company match", "Company vehicle for site visits", "Flexible schedule options"]',
    CURRENT_DATE - INTERVAL '15 days',
    CURRENT_DATE + INTERVAL '45 days',
    true
),
(
    'Drywall Installation Apprentice',
    'Installation',
    'Calgary, AB',
    'Full-time',
    'Entry-level',
    'Learn the drywall trade hands-on with our skilled installation team. No experience required - we''ll train you from the ground up with our comprehensive apprenticeship program.',
    '["Assist journeyman installers with drywall hanging", "Learn proper measuring, cutting, and hanging techniques", "Help maintain job site cleanliness and organization", "Assist with material handling and preparation", "Participate in regular training sessions"]',
    '["High school diploma or equivalent", "Physical ability to lift up to 50 lbs regularly", "Reliable transportation", "Strong work ethic and willingness to learn", "Basic math and measuring skills"]',
    '["Starting pay: $16-18/hr with regular increases as skills develop", "Paid on-the-job training and mentorship", "Health insurance eligibility after 90 days", "Clear path for advancement to journeyman level", "Tool program to help build your equipment over time"]',
    CURRENT_DATE - INTERVAL '7 days',
    CURRENT_DATE + INTERVAL '60 days',
    false
);
